// POEMAS DA LÍNGUA PORTUGUESA
// Cada poema tem: id, title, author, excerpt, difficulty
window.POEMS = [
    // ===== FÁCIL =====
    { id:"p1",  title:"Tabacaria",        author:"Fernando Pessoa",            excerpt:"Não sou nada. Nunca serei nada. Não posso querer ser nada. À parte isso, tenho em mim todos os sonhos do mundo.",                                                                              difficulty:"easy" },
    { id:"p2",  title:"Profundamente",    author:"Manuel Bandeira",            excerpt:"Quando ontem adormeci na noite de São João havia alegria e rumor estrondos de bombas luzes de Bengala vozes cantigas e risos.",                                                                 difficulty:"easy" },
    { id:"p3",  title:"Quadrilha",        author:"Carlos Drummond de Andrade", excerpt:"João amava Teresa que amava Raimundo que amava Maria que amava Joaquim que amava Lili que não amava ninguém.",                                                                                  difficulty:"easy" },
    { id:"p4",  title:"José",             author:"Carlos Drummond de Andrade", excerpt:"E agora, José? A festa acabou, a luz apagou, o povo sumiu, a noite esfriou, e agora, José?",                                                                                                   difficulty:"easy" },
    { id:"p5",  title:"O Bicho",          author:"Manuel Bandeira",            excerpt:"Vi ontem um bicho na imundície do pátio catando comida entre os detritos. Quando achava alguma coisa, não examinava nem cheirava: engolia com voracidade.",                                     difficulty:"easy" },
    { id:"p6",  title:"Pneumotórax",      author:"Manuel Bandeira",            excerpt:"Febre, hemoptise, dispneia e suores noturnos. A vida inteira que podia ter sido e que não foi.",                                                                                                difficulty:"easy" },
    { id:"p7",  title:"Retrato",          author:"Cecília Meireles",           excerpt:"Eu não tinha este rosto de hoje, assim calmo, assim triste, assim magro, nem estes olhos tão vazios, nem o lábio amargo.",                                                                      difficulty:"easy" },
    { id:"p8",  title:"Motivo",           author:"Cecília Meireles",           excerpt:"Eu canto porque o instante existe e a minha vida está completa. Não sou alegre nem sou triste: sou poeta.",                                                                                     difficulty:"easy" },
    { id:"p9",  title:"Autopsicografia",  author:"Fernando Pessoa",            excerpt:"O poeta é um fingidor. Finge tão completamente que chega a fingir que é dor a dor que deveras sente.",                                                                                          difficulty:"easy" },
    { id:"p10", title:"Liberdade",        author:"Cecília Meireles",           excerpt:"Suspiraremos, então, em romaria, à pátria do herói, dileta do Senhor: e nem o tempo nos roubará a memória.",                                                                                   difficulty:"easy" },
    { id:"p11", title:"Mensagem",         author:"Fernando Pessoa",            excerpt:"Deus quer, o homem sonha, a obra nasce. Deus quis que a terra fosse toda uma, que o mar unisse, já não separasse.",                                                                             difficulty:"easy" },
    { id:"p12", title:"Trem de Ferro",    author:"Manuel Bandeira",            excerpt:"Café com pão, café com pão, café com pão. Virge Maria, que foi isso, maquinista?",                                                                                                              difficulty:"easy" },

    // ===== MÉDIO =====
    { id:"p13", title:"Canção do Exílio",    author:"Gonçalves Dias",               excerpt:"Minha terra tem palmeiras, onde canta o sabiá; as aves, que aqui gorjeiam, não gorjeiam como lá.",                                                                                           difficulty:"medium" },
    { id:"p14", title:"Mar Português",       author:"Fernando Pessoa",              excerpt:"Ó mar salgado, quanto do teu sal são lágrimas de Portugal! Por te cruzarmos, quantas mães choraram, quantos filhos em vão rezaram!",                                                          difficulty:"medium" },
    { id:"p15", title:"Soneto de Fidelidade",author:"Vinicius de Moraes",           excerpt:"De tudo, ao meu amor serei atento antes, e com tal zelo, e sempre, e tanto que mesmo em face do maior encanto dele se encante mais meu pensamento.",                                         difficulty:"medium" },
    { id:"p16", title:"A Rosa de Hiroshima", author:"Vinicius de Moraes",           excerpt:"Pensem nas crianças mudas telepáticas. Pensem nas meninas cegas inexatas. Pensem nas mulheres rotas alteradas.",                                                                              difficulty:"medium" },
    { id:"p17", title:"Poema de Sete Faces", author:"Carlos Drummond de Andrade",   excerpt:"Quando nasci, um anjo torto desses que vivem na sombra disse: Vai, Carlos! ser gauche na vida.",                                                                                             difficulty:"medium" },
    { id:"p18", title:"Mãos Dadas",          author:"Carlos Drummond de Andrade",   excerpt:"Não serei o poeta de um mundo caduco. Também não cantarei o mundo futuro. Estou preso à vida e olho meus companheiros.",                                                                     difficulty:"medium" },
    { id:"p19", title:"Tecendo a Manhã",     author:"João Cabral de Melo Neto",     excerpt:"Um galo sozinho não tece uma manhã: ele precisará sempre de outros galos. De um que apanhe esse grito que ele e o lance a outro.",                                                            difficulty:"medium" },
    { id:"p20", title:"Ou Isto Ou Aquilo",   author:"Cecília Meireles",             excerpt:"Ou se tem chuva e não se tem sol, ou se tem sol e não se tem chuva! Ou se calça a luva e não se põe o anel.",                                                                                difficulty:"medium" },
    { id:"p21", title:"Os Lusíadas",         author:"Luís de Camões",               excerpt:"As armas e os barões assinalados que da ocidental praia lusitana, por mares nunca de antes navegados, passaram ainda além da Taprobana.",                                                     difficulty:"medium" },
    { id:"p22", title:"Amor é Fogo",         author:"Luís de Camões",               excerpt:"Amor é fogo que arde sem se ver; é ferida que dói e não se sente; é um contentamento descontente; é dor que desatina sem doer.",                                                             difficulty:"medium" },

    // ===== DIFÍCIL =====
    { id:"p23", title:"No Meio do Caminho",           author:"Carlos Drummond de Andrade", excerpt:"No meio do caminho tinha uma pedra, tinha uma pedra no meio do caminho, tinha uma pedra; no meio do caminho tinha uma pedra.",                                                        difficulty:"hard" },
    { id:"p24", title:"Vou-me Embora pra Pasárgada",  author:"Manuel Bandeira",            excerpt:"Vou-me embora pra Pasárgada. Lá sou amigo do rei. Lá tenho a mulher que eu quero na cama que escolherei.",                                                                          difficulty:"hard" },
    { id:"p25", title:"Morte e Vida Severina",         author:"João Cabral de Melo Neto",  excerpt:"O meu nome é Severino, não tenho outro de pia. Como há muitos Severinos, que é santo de romaria.",                                                                                  difficulty:"hard" },
    { id:"p26", title:"Confidência do Itabirano",      author:"Carlos Drummond de Andrade", excerpt:"Alguns anos vivi em Itabira. Principalmente nasci em Itabira. Por isso sou triste, orgulhoso: de ferro.",                                                                           difficulty:"hard" },
    { id:"p27", title:"Aninha e Suas Pedras",          author:"Cora Coralina",              excerpt:"Não te deixes destruir, ajuntando pedras novas e construindo novos poemas. Recria tua vida, sempre, sempre.",                                                                       difficulty:"hard" },
    { id:"p28", title:"Receita de Mulher",             author:"Vinicius de Moraes",         excerpt:"As muito feias que me perdoem, mas beleza é fundamental. É preciso que haja qualquer coisa de flor em tudo isso.",                                                                  difficulty:"hard" },
    { id:"p29", title:"As Sem-Razões do Amor",         author:"Carlos Drummond de Andrade", excerpt:"Eu te amo porque te amo. Não precisas ser amante, e nem sempre sabes sê-lo. Eu te amo porque te amo.",                                                                             difficulty:"hard" },
    { id:"p30", title:"Ode Triunfal",                  author:"Álvaro de Campos",           excerpt:"À dolorosa luz das grandes lâmpadas elétricas da fábrica tenho febre e escrevo. Escrevo rangendo os dentes, fera para a beleza disto.",                                            difficulty:"hard" },
];
